on:
  push:
    tags:
      - "*"

name: Package the theme
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Package VS Code extension
        id: package
        uses: nhedger/package-vscode-extension@v1
      - name: Publish VS Code extension artifact
        uses: actions/upload-artifact@v3
        with:
            name: vscode-theme-darkgeem.vsix
            path: ${{ steps.package.outputs.packagePath }}
